### PR TITLE
Cleaned up documentation, wrote some pros/cons

### PR DESCRIPTION
**Pull request by charminULTRA**
I edited the section to hopefully make it easier to read. I'd also propose we add a warning that the T-Echo is very buggy currently and people should be warned to check the current status of bugs or check with the community before buying, but I'll leave this up to some else's discretion.

### CODE REVIEW

**Comment by garthvh** [comment]
Do you mind adding a recommendation that that NRF52 have 10-20x less battery draw?  That is the other relevant spec.

**Comment by charminULTRA** [comment]
> Do you mind adding a recommendation that that NRF52 have 10-20x less battery draw? That is the other relevant spec.

Updated to say it draws 90-95% less power, does that work?

**Comment by jfirwin** [comment]
I think that works well unless @garthvh has any objections? If not, we can go ahead and merge this.

**Comment by garthvh** [comment]
Looks good

**Pull request merged**
