### PR TITLE
Add Financial Contribution Option to FAQ

### PR DESCRIPTION
**Pull request by pdxlocations**
[preview link](https://sandbox-git-faq-01-pdxlocations.vercel.app/docs/faq/?openFaqItems-general=%3Ar1%3A)

### CODE REVIEW

**Comment by pdxlocations** [comment]
> > [preview link](https://sandbox-git-faq-01-pdxlocations.vercel.app/docs/faq/?openFaqItems-general=%3Ar1%3A)
> 
> Might I suggest we send them to the /docs/contributing page? "There are multiples to contribute to the project" yada yada and link to the contributing page which has ALL the info?

I don't think most people want to read through the entire page to get the answers they're looking for and I imo it's not a great idea to add clicks between the user and a financial contribution, if that's what they're looking for.   I added a link to the page "for more details".   How about that?

I'm totally open to changing this wording though.  I just want to get this info into the users hands efficiently. 

Too many of our pages go on and on and I just lose interest.  Short concise instructions/information is easier to consume, for pages like FAQ especially.

**Comment by pdxlocations** [comment]
Continuing my thought process:  Should the FAQ page be just a list of questions with pointers to answers?  Or a list of questions with answers.  (or just a list of questions)

**Comment by pdxlocations** [comment]
> Seems useless to have all that information and then not even use it. 
I don't understand what you mean by this.  The contributing page is great for the few users that can and want to read.  It has a top-level link and is easy to find.  

My question is what good is an FAQ page if it just directs you away from itself.  Shouldn't it contain at least some answers to the questions?

**Review by tekstrand — APPROVED** [review]
FAQ page with links to other pages with answers is a big "no no" by web standards. You need to have the answers on the page that people arrive on, at least from a Search Engine perspective.

I like your approach here. We give the basics, and link to a separate page for more detailed information.

**Pull request merged**
