### PR TITLE
Fixed discrepancy

### PR DESCRIPTION
**Pull request by IZ1IVA**

### CODE REVIEW

**Comment by garthvh** [comment]
This looks like a dup

**Review by garthvh — COMMENTED** [review]
Looks like the merge failed and there is a line of extra booleans that needs to be deleted

**Comment by IZ1IVA** [comment]
> This looks like a dup

It's not, I've seen this discrepancy in the docs immediately after I've sent in the PR for the other one. Sorry!

**Comment by IZ1IVA** [comment]
> Looks like the merge failed and there is a line of extra booleans that needs to be del

**Review by caveman99 — APPROVED** [review]

**Comment by caveman99** [comment]
There, I fixed it ;-)

**Pull request merged**
