### PR TITLE
Add German language telegram groups

### PR DESCRIPTION
**Pull request by caveman99**

### CODE REVIEW

**Comment by caveman99** [comment]
I am aware of that and we are in the process of changing that. For Regio I have no immediate idea for a catchy name that best describes the function without violating the letter of the grant. The group sprung out of necessity not to clutter the main group.

**Comment by caveman99** [comment]
Icons have been changed.

**Comment by pdxlocations** [comment]
> Icons have been changed.

The D-A-CH looks superb!  The other group though seems to me to still be in conflict with the trademark guidelines for both naming and logo use.  What do you think?

**Comment by caveman99** [comment]
> The D-A-CH looks superb! The other group though seems to me to still be in conflict with the trademark guidelines for both naming and logo use. What do you think?

It's not easy. The current changes have caused a bit of a stir already. Main Group is D-A-CH. The regio group is for local (or state) coordination of network buildup. It is linked after signing in to the main group though, so we might as well remove it from the listing.

**Review by pdxlocations — APPROVED** [review]

**Pull request merged**
