### PR TITLE
Update local-groups.mdx

### PR DESCRIPTION
**Pull request by snag1es**
Bulgarian Meshtastic Community Group

### CODE REVIEW

**Comment by pdxlocations** [comment]
Hello, and thank you for your interest and support of the project!  However, I have noticed that your facebook group does not follow the [trademark guidelines](https://meshtastic.org/docs/legal/licensing-and-trademark/#social-media).

- Please change your logo to something of your own design, move the official logo to a secondary position, or use [the M-Powered Logo](https://github.com/meshtastic/design/tree/master/Meshtastic%20Powered%20Logo).

- Please change the name of your group so that it does not indicate official sponsorship. For example: "Bulgarian Meshtastic Community Group" would be fine, but "Meshtastic Bulgaria" is not.

- PR's cannot be merged unless the contributor signs the CLA.

Thanks again and I look forward to adding your group to the site!

**Comment by snag1es** [comment]
Shall we reopen this issue

**Comment by pdxlocations** [comment]
Looks like the Logo is fixed and the CLA is signed.  There's just group name in the PR to address.  Nice!

**Comment by pdxlocations** [comment]
closed in favor of #1583

**Pull request closed without merging**
