### PR TITLE
Renamed "Firmware" tab to "Downloads" and updated the README

### PR DESCRIPTION
**Pull request by nuxnik**
Here are a few basic updates, as we discussed on discord. 

1. Renamed "Firmware" tab to "Downloads" and updated the links to it in the documentation. 
2. Updated the README to include very basic installation instructions for developers.

Note: The eventually the downloads page should be refactored to include the other repositories: Android, protobufs, meshtastic.js etc.

### CODE REVIEW

**Comment by sachaw** [comment]
making this a downloads page, should require more than just links to the firmware.
Could you please extend this PR to include the other downloadable software items: Android app etc.

**Comment by garthvh** [comment]
Having a dedicated firmware tab has really reduced firmware questions, do we want to do this for a temporary APK download when it should be back in the store soon?

**Comment by nuxnik** [comment]
First of all, thanks for the comments! I am new here and am excited to help out. I think having a "download" page is a standard convention for a software project. Most software projects I can think of, have a download link. It is intuitive. Firmware is very specific and refers to well... firmware. My understanding of that page is a place where users can download software. It is a download page. "Firmware" excludes any other software and is limited to one subset of the software that is offered in the meshtastic "suite". Just my two cents.

**Comment by garthvh** [comment]
> First of all, thanks for the comments! I am new here and am excited to help out. I think having a "download" page is a standard convention for a software project. Most software projects I can think of, have a download link. It is intuitive. Firmware is very specific and refers to well... firmware. My understanding of that page is a place where users can download software. It is a download page. "Firmware" excludes any other software and is limited to one subset of the software that is offered in the meshtastic "suite". Just my two cents.

While this may be true if you are starting a website from scratch, we have lots of people who have provided links and discussion on discourse and discord telling people how to get firmware which is a real common issue new users have. I used to get a lot of these requests directly before we added the firmware tab and am not real excited about fielding those requests again.

**Comment by garthvh** [comment]
@andrekir Thoughts?

**Comment by nuxnik** [comment]
> > First of all, thanks for the comments! I am new here and am excited to help out. I think having a "download" page is a standard convention for a software project. Most software projects I can think of, have a download link. It is intuitive. Firmware is very specific and refers to well... firmware. My understanding of that page is a place where users can download software. It is a download page. "Firmware" excludes any other software and is limited to one subset of the software that is offered in the meshtastic "suite". Just my two cents.
> 
> While this may be true if you are starting a website from scratch, we have lots of people who have provided links and discussion on discourse and discord telling people how to get firmware which is a real common issue new users have. I used to get a lot of these requests directly before we added the firmware tab and am not real excited about fielding those requests again.

Ah I see... however if it only about the existing URL links floating around the web, we can redirect the routing and define a canonical URL tag for SEO.

**Comment by garthvh** [comment]
> Ah I see... however if it only about the existing URL links floating around the web, we can redirect the routing and define a canonical URL tag for SEO.

I don't think this will help much, much of this info is on discussion forums for overloading or ATAK that are outside of Meshtastic's control.  I do not love the idea of this being merged in isolation without a bunch of other UX improvements to the website this is just going to cause confusion and cost me time.

**Comment by nuxnik** [comment]
Understood, I don't want to make extra work for anyone :)

**Pull request closed without merging**
