### PR TITLE
local-groups.mdxを更新する

### PR DESCRIPTION
**Pull request by Goyath**

### CODE REVIEW

**Comment by pdxlocations** [comment]
Thank you so much for your patience.  The only issue remaining is the improper use of the "M" logo.  Using this trademark is only allowed if it is used "secondary" to your own group logo, or you may use the "M Powered" design without such restrictions.
image

**Comment by Goyath** [comment]
IMG_0022
We've removed the logo. What do you think?

**Review by pdxlocations — APPROVED** [review]
fantastic!

**Comment by Goyath** [comment]
Thank you for your advice.

**Pull request merged**
