### PR TITLE
Add wifi bluetooth annotation

### PR DESCRIPTION
**Pull request by jfirwin**
I also removed the wifi section from software/device and consolidated so there's one less wifi page now.

### CODE REVIEW

**Comment by jfirwin** [comment]
I'm going to consolidate the WiFi page in the web interface on the branch. I'll add that in a little while.

**Comment by jfirwin** [comment]
Links to the relevant changes:
- [software/web/configuration](https://meshtastic-lyuoyi8j6-jfirwin.vercel.app/docs/software/web/web-config-software#wifi-configuration) - redirected instructions to wifi settings page
- [settings/wifi](https://meshtastic-lyuoyi8j6-jfirwin.vercel.app/docs/settings/wifi#details) - added screen details to wifi page details

**Comment by sachaw** [comment]
Looks good, I'll need to start some webui docs, as that page is completely obsolete.
I'd like to make the "Examples" sections unified in there layout across the settings, as I think there quite good. and maybe an obvious "Jump to examples" link or something at the top of the page, as reading all the technical docs about each flag or param can be intimidating.

**Comment by jfirwin** [comment]
Yeah I agree, it's gotten a bit out of hand. I have considered moving the examples up above the settings table, but below the overview. That way we can put user friendly configurations up top, and people can read into the nitty gritty details at the bottom of the page.

**Pull request merged**
