### PR TITLE
Update linux-native-hardware.mdx

### PR DESCRIPTION
**Pull request by SpudGunMan**
## What did you change
add note for elevated SSL access

## Why did you change it
to help others remember

### CODE REVIEW

**Review by pdxlocations — COMMENTED** [review]
I'm not understanding what this note means.  What action is needed for the user?

**Comment by SpudGunMan** [comment]
just to have a note, I dont know its intuitive in the example, that because port 443 is in use sudo is required in a lot of cases

**Comment by pdxlocations** [comment]
Sorry, I'm still confused.  What is the command that requires sudo?

**Comment by SpudGunMan** [comment]
this just calls out sudo it sounds like its not handy closing

**Pull request closed without merging**
