### PR TITLE
Added social links to the footer

### LINKED ISSUE #225: Community links
There are other sources in the meshtastic project universe that should be displayed more prominently in the docs so they can be easily found:

1. YouTube Channel - https://www.youtube.com/meshtastic
2. Discord server - https://discord.com/invite/UQJ5QuM7vq
3. Forum - https://meshtastic.discourse.group
3. Github - https://github.com/meshtastic

Suggestion: 

1. Add these links to the footer of the page so they are visible on every page.
2. Add a "Community" page to the documentation which lists the links.

Thoughts?

### PR DESCRIPTION
**Pull request by nuxnik**
Added social links to the footer of the page. No  

resolves #225

### CODE REVIEW

**Comment by jfirwin** [comment]
We spoke about this and @nuxnik is going to do some edits and add more links.

**Review by jfirwin — CHANGES_REQUESTED** [review]
We already discussed adding more links and additional columns to the footer like the docusaurus website.

**Comment by nuxnik** [comment]
@jfirwin - I added the links we talked about. Check it out: https://meshtastic-mah0mj2lz-nuxnik.vercel.app

**Comment by jfirwin** [comment]
Looks awesome! Thanks!

**Pull request merged**
