### PR TITLE
Update local-groups.mdx

### PR DESCRIPTION
**Pull request by Domiziano-R**
add italian discord server as local comm

### CODE REVIEW

**Comment by pdxlocations** [comment]
Hi @Domiziano-R, could you sign the CLA?  Thank you!

**Comment by Domiziano-R** [comment]
> Hi @Domiziano-R, could you sign the CLA? Thank you!

Done , 
thank you

**Comment by pdxlocations** [comment]
I want to merge this but I'm not sure if the logo violates trademark usage.  @rcarteraz ?
Screenshot 2024-04-22 at 8 39 21 AM

**Comment by Domiziano-R** [comment]
if there is a problem i can change for sure

**Comment by pdxlocations** [comment]
> if there is a problem i can change for sure

I've asked on the #trademark discord channel.
https://discord.com/channels/867578229534359593/1047263557525458994/1231993916794998934

**Comment by Domiziano-R** [comment]
i changed the name to Mesh ITA Club , is acceptable ?

**Comment by pdxlocations** [comment]
> i changed the name to Mesh ITA Club , is acceptable ?

the name is great, thanks for doing that!   I'm just holding off on the merge since there is some discussion on acceptable logo usage.

**Comment by Domiziano-R** [comment]
mesh-ita2

i changed the logo , let me know if if ok or not
Thank you

**Comment by pdxlocations** [comment]
> @pdxlocations i dont want bothering you , but there is some news ? Is the new logo ok with the rule ? Let me know
> 
> Thank you

No bother at all!  I've asked on Discord.  Hopefully an admin will chime in when they have time.

**Comment by pdxlocations** [comment]
> Is the new logo ok with the rule ?

Could you have a look at the discussion in the Discord?
https://discord.com/channels/867578229534359593/1047263557525458994/1239959046488981635

**Comment by pdxlocations** [comment]
I believe the ask is to have the M logo below the group name so it is secondary.  I love the designs though!

**Comment by Domiziano-R** [comment]
If is needed i can move the M below, let me know is just 3 click
tnx

**Comment by pdxlocations** [comment]
IMO moving it to the bottom seems acceptable, though in the long run, a unique logo for your club that didn't rely on the trademark M would be something to consider.

**Comment by Domiziano-R** [comment]
mesh-ita3r
Done :)

btw i dont get what u mean :"a unique logo for your club that didn't rely on the trademark M would be something to consider."

Is not "compliant" now , i should remove the M ?

thank you

**Comment by pdxlocations** [comment]
> btw i dont get what u mean :"a unique logo for your club that didn't rely on the trademark M would be something to consider."
Here's an example of a logo that @rcarteraz is working on
Screenshot_2024-05-14_at_12 15 43_PM

**Review by pdxlocations — APPROVED** [review]

**Comment by pdxlocations** [comment]
Thanks for your patience with this.  The trademark is relatively new and guidelines are still being developed by the community.

**Comment by pdxlocations** [comment]
> mesh-ita3r Done :)
> 
> btw i dont get what u mean :"a unique logo for your club that didn't rely on the trademark M would be something to consider."
> 
> Is not "compliant" now , i should remove the M ?
> 
> thank you

Looks good, let me know when this change is live and I'll merge

**Comment by Domiziano-R** [comment]
immagine

is live 
thank ypu

**Pull request merged**
