### PR TITLE
Work In Progress: Automatic Documentation PDF Generation

### PR DESCRIPTION
**Pull request by tekstrand**
## What
Solves #226 
1. Adds `docusaurus-prince-pdf` as dev dependency
2. Some new css that makes tabs hidden but their content visible when printing pages
3. A new GitHub action that
    - Installs [Prince xml](https://www.princexml.com/)
    - Generates a PDF
    - Fetches access token from Meshtastic org github app
    - Pushes the generated pdf to the `docs` branch of `meshtastic/artifacts` as `Meshtastic-Documentation-${DATE_TIME}_${{ github.sha }}.pdf`

## Why
- We have users who would like to maintain offline documentation
- We have [users with brain injuries](https://www.reddit.com/r/meshtastic/comments/1au18gr/offline_manual/) who have a hard time reading our docs on screen
- All tabs now have headings after #1021 so the actual tab can be hidden and the content kept visible

### CODE REVIEW

**Review by caveman99 — APPROVED** [review]

**Comment by tekstrand** [comment]
@sachaw updated to match firmware action. Not sure how to test it in this configuration

**Comment by sachaw** [comment]
Just trying to see if I can make the `ARTIFACTS_TOKEN` an org level token

**Comment by tekstrand** [comment]
@sachaw @thebentern seems like this workflow skipped the artifacts step because the criteria was not met
https://github.com/meshtastic/meshtastic/blob/master/.github/workflows/pdf.yml#L33
`if: ${{ github.event_name == 'pull_request_target' || github.event_name == 'pull_request' }}`

I copied this directly from the firmware builds as suggested. What is the workflow over there that successfully triggers it?

**Comment by tekstrand** [comment]
This should fix it https://github.com/meshtastic/meshtastic/pull/1063

**Pull request merged**
