### PR TITLE
Documentation for channel settings via CLI

### PR DESCRIPTION
**Pull request by acabey**
Updated CLI documentation to replace deprecated `setchan` examples with `ch-set` and added a `ch-del` example using `ch-index` as this was unclear to me.

### CODE REVIEW

**Comment by sachaw** [comment]
This should not be fixed, please check if there's anything in your pr that has been missed and I'll merge it.

**Comment by acabey** [comment]
> This should not be fixed, please check if there's anything in your pr that has been missed and I'll merge it.

I'm sorry what should  not be fixed?

**Comment by sachaw** [comment]
now*

**Comment by acabey** [comment]
Understood. Fixed merge conflicts - the cli.md file is good all that I modified and it is good to merge.

**Pull request merged**
