### PR TITLE
Add Las Vegas to community list

### PR DESCRIPTION
**Pull request by trosel**

### CODE REVIEW

**Review by pdxlocations — CHANGES_REQUESTED** [review]
Hello @trosel!  I'm looking forward to merging your PR but first:
1. Could you sign the CLA?
2. The logo used for your discord server doesn't "mesh" with the [trademark guidelines](https://meshtastic.org/docs/legal/licensing-and-trademark/#meshtastic-trademark-policy--brand-guidelines).  Please use the [M-Powered logo](https://github.com/meshtastic/design/tree/master/Meshtastic%20Powered%20Logo) or something of your own creation.
Thanks!

**Comment by trosel** [comment]
> 2\. The logo used for your discord server doesn't "mesh" with the [trademark guidelines](https://meshtastic.org/docs/legal/licensing-and-trademark/#meshtastic-trademark-policy--brand-guidelines).  Please use the [M-Powered logo](https://github.com/meshtastic/design/tree/master/Meshtastic%20Powered%20Logo) or something of your own creation.

The logo for the discord server is "something of our own creation". It says "vegas mesh" very clearly. Can you advise what more should be done?

**Comment by trosel** [comment]
> In my opinion, adding your name to another's brand does not make it your creation.

"Another's brand"? Is meshtastic a private corporation or something? I thought it was an open source project. Don't you want all of the local communities to have logo so that people know it is meshtastic? 

The image you just pasted there is fine. I can ask them to swap to that. But now it's not clear that we use meshtastic at all.

**Comment by tekstrand** [comment]
Hey @trosel thanks for working with us to make the change. Meshtastic is open source, as you say, but is an LLC that needs to protect it's trademark. The "M" logo is the trademark, as laid out in our [guidelines](https://meshtastic.org/docs/legal/licensing-and-trademark/#meshtastic-trademark-policy--brand-guidelines). The M-Powered logo is the community use version, which you'll find _most_ community groups using. A few out there do use completely custom logos. Entirely up to you which direction to go there except that you cannot use the trademarked logo. The guidelines do a great job of laying things out

**Comment by trosel** [comment]
I’m working with the server admin to change it to something else. 

Just as some feedback, the problem with the m-powered logos is that there’s nothing about the location. 

So our choices are either

1. Nothing about meshatastic
2. Nothing about the location 

Neither of these are desirable.

**Comment by pdxlocations** [comment]
Here's what the local Portland folks are using which seems fine to me (I don't own the trademark).  It's clear that it's not an officially sponsored group but also shows the location and the affiliation with Meshtastic.  Your location is also clearly defined in the group name.  I encourage you to get creative, and check out some of the other groups linked from this page. Your choices are only limited by your imagination. 
Screenshot 2024-08-25 at 5 52 42 PM

**Comment by trosel** [comment]
Okay, we swapped to this AI generated one. Good to go!

**Review by pdxlocations — APPROVED** [review]

**Pull request merged**
