### PR TITLE
Attempting to clarify what send_owner_interval is

### PR DESCRIPTION
**Pull request by thebentern**
My notes are based on this information: https://meshtastic.discourse.group/t/real-time-communication-and-location-update/1990/2

### CODE REVIEW

**Comment by jfirwin** [comment]
This looks great. I'm waffling back and forth on wether we should include `(pings)` in the table where you removed seconds. Any thoughts? I'm ok either way, as it's described below in the setting section

**Comment by thebentern** [comment]
Maybe (per network ping). 
I'd like to actually define what a ping is in some section of the docs. It's another one of those ambiguous terms that gets thrown around a lot but is entirely different in the context of the meshtastic mesh behavior. I _think_ it means position broadcasts and owner info broadcasts, but I can't say for certain.

**Comment by jfirwin** [comment]
Maybe `(network ping interval)` or `(each x/interval pings)`?

I agree that pings should be more well defined. We can add a  html commented out TODO mentioning to link to that.
```
<!--- TODO add link to ping explanation --->
```

**Comment by thebentern** [comment]
> Maybe `(network ping interval)` or `(each x/interval pings)`?
> 
> I agree that pings should be more well defined. We can add a html commented out TODO mentioning to link to that.
> 
> ```
> 
> ```

Maybe send per `(sent per x network pings)`

**Comment by jfirwin** [comment]
`(sent every x network pings)`? I think every might be a little more clear than per, but I think you're right. I'm good with either.

**Comment by thebentern** [comment]
> `(sent every x network pings)`? I think every might be a little more clear than per, but I think you're right. I'm good with either.
Perfect!

**Comment by sachaw** [comment]
Ready to merge?

**Comment by jfirwin** [comment]
I believe so! I've been on mobile all weekend so I haven't been able to "approve" it.

**Pull request merged**
