### PR TITLE
Add Lithuanian Facebook group

### PR DESCRIPTION
**Pull request by drawgas**

### CODE REVIEW

**Review by tekstrand — APPROVED** [review]

**Comment by pdxlocations** [comment]
@tekstrand @rcarteraz I believe this group violates trademark guidelines.

**Comment by pdxlocations** [comment]
Screenshot 2024-04-22 at 8 24 48 AM

**Comment by pdxlocations** [comment]
woof, I'd suggest we remove them and/or reach out to have the names changed

**Comment by tekstrand** [comment]
https://discord.com/channels/867578229534359593/1047263557525458994/1231992540190871623

**Pull request merged**
