### PR TITLE
Antenna

### PR DESCRIPTION
**Pull request by apt105**
See https://meshtastic-5r4yfab6v-apt105.vercel.app/docs/hardware/antenna

### CODE REVIEW

**Comment by jfirwin** [comment]
Looks great @apt105. That's a lot of material to digest, so kudos to you for putting it together!

**Comment by apt105** [comment]
Nah, mainly a copy and paste with a bit of proof reading. Just doing little straightforward bits atm.

**Comment by sachaw** [comment]
If you could just add a few admonitions, I will merge this

**Comment by apt105** [comment]
How's this? https://meshtastic-jv0pngrd2-apt105.vercel.app/docs/hardware/antenna

**Pull request merged**
