### PR TITLE
Update local-groups.mdx

### PR DESCRIPTION
**Pull request by smuniz**

### CODE REVIEW

**Review by tekstrand — CHANGES_REQUESTED** [review]
Hi @smuniz - this group will need to change it's name to conform to the Meshtastic LLC guidelines https://meshtastic.org/docs/legal/licensing-and-trademark/#licensing

In short, the name will need to be changed to something other than Meshtastic Argentina

**Comment by smuniz** [comment]
hi there! I see other names in the list like "Meshtastic XXX" hence we decided to go with it.

Would "Meshtastic Argentina Community" be ok?

**Comment by tekstrand** [comment]
Yes, adding `Community` will work. We are working with those other groups to have them change theirs as well.

**Comment by pdxlocations** [comment]
This is amazing, lol!
https://github.com/Meshtastic-Argentina/meshtastic_grumpy_bot

**Comment by tekstrand** [comment]
Hey @smuniz there are still a few things that need to change. Thank you for understanding!

Screenshot 2024-08-29 at 7 47 21 AM

**Comment by smuniz** [comment]
Thanks a lot for the heads up and sorry for any inconvenience. I've corrected the names on Github and also added a trademark notice (copy&pasted from Licensing & trademark Rules) in there to avoid any problems. Please don't hesitate to let us know if more changes are required.

**Review by tekstrand — APPROVED** [review]

**Pull request merged**
