### PR TITLE
Add battery purchase instructions

### PR DESCRIPTION
**Pull request by jberenhaus**
Added instructions on how to purchase a battery and some preferences

### CODE REVIEW

**Comment by sachaw** [comment]
I'd change the wording, as we have many people who reside outside the US.

Make it just an option instead of a recommendation.

**Comment by jfirwin** [comment]
I was thinking along the same lines. If we get that changed we can merge it in.

Thanks for your contribution!

**Comment by jberenhaus** [comment]
Oh good call, I updated it to say "One of our favorite places for folks in the US to buy the necessary 18650 Li-Ion battery is..."

Let me know if there's any favorite places to buy it outside the US you want me to add or any other wording recommendations :)

**Comment by sachaw** [comment]
Tweaked it a little more, now nobody can complain if they don't get the results they expected.

Thanks for the pr

**Pull request merged**
