### PR TITLE
Update local-groups.mdx

### PR DESCRIPTION
**Pull request by puzzled-pancake**
Added New Zealand facebook and discord to local community docs

### CODE REVIEW

**Review by pdxlocations — CHANGES_REQUESTED** [review]
Hi @puzzled-pancake , it's exciting to see your interest in Meshtastic and we'd love to include your group in the community listings. However, I cannot merge this request as the group name and logo do not agree with the Trademark Usage Guidelines:
https://meshtastic.org/docs/legal/licensing-and-trademark/#social-media

Please review these requirements and once the group is rebranded with it's own identity I look forward to adding it to the official documentation. Please comment here if you have any questions. Thank you.

**Comment by puzzled-pancake** [comment]
> Hi @puzzled-pancake , it's exciting to see your interest in Meshtastic and we'd love to include your group in the community listings. However, I cannot merge this request as the group name and logo do not agree with the Trademark Usage Guidelines: https://meshtastic.org/docs/legal/licensing-and-trademark/#social-media
> 
> Please review these requirements and once the group is rebranded with it's own identity I look forward to adding it to the official documentation. Please comment here if you have any questions. Thank you.

No worries we are polling what to change the names too.

**Comment by pdxlocations** [comment]
Hey @puzzled-pancake, do you know who owns https://meshtastic.co.nz/ ?
There may be a trademark issue with this as well
https://meshtastic.org/docs/legal/licensing-and-trademark/#domain-names

**Comment by puzzled-pancake** [comment]
Everything should be inline now hopefully
I will see if I can find the owner of https://meshtastic.co.nz/

**Comment by pdxlocations** [comment]
I'm so sorry, I don't believe the facebook banner falls within the allowable use:

"Meshtastic also grants communities and user groups permission to use the Meshtastic logo, provided it is displayed in a secondary position to the group's primary branding"

Screenshot 2024-09-14 at 10 31 52 PM

**Comment by puzzled-pancake** [comment]
I removed the facebook group and just added the discord.... that should meet all the requirements

**Review by pdxlocations — APPROVED** [review]
The Facebook group is still in violation of the Trademark Usage but I can now merge this PR.  Thank you for your patience and cooperation!

**Pull request merged**
