### PR TITLE
Update FrequencyCalculator.tsx

### PR DESCRIPTION
**Pull request by WOD-MN**
adding nepal as a new region

### CODE REVIEW

**Comment by WOD-MN** [comment]
add nepal as new region

**Comment by WOD-MN** [comment]
add nepal as new region

**Comment by caveman99** [comment]
You can't add a region to the calculator that is not in the actual firmware, sorry.

**Comment by WOD-MN** [comment]
how to add the region in the firmware? wanna add the Nepal as a new regin with 86-868 mhz and 100% duty cycle with 30dBm ! it's free frequency band for IoT in Nepal

**Pull request closed without merging**
