### PR TITLE
Remove Guides Section

### PR DESCRIPTION
**Pull request by rcarteraz**
Okay, I'm proposing we remove the "Guides" section in the docs sidebar menu. The reasoning? One, it cluttered up the sidebar since it was between "Getting Started" and "Configuration." Two, half of the items within the section were linked from other sections, making it redundant and the remaining items can easily be folded into other sections and still make sense. And lastly, by removing it, the menu flows together better than with it. 

Updates made to remove guides section:

- "Factory Reset NRF52 Devices" was moved to `docs/getting-started/flashing-firmware/nrf52`
- "Setup GPIO Peripherals" was moved to `docs/configuration/`. Reasoning for this is we already have a "guide" on Rak GPIO Mapping so it flows with that. 
- "Convert RAK4631-R to RAK4631" was moved to `docs/hardware/devices/rak` which seemed the most appropriate location. However, a case could be made to move it to `docs/getting-started/flashing-firmware/nrf52` so I'm open to that idea as well. 
- The items that were linked and visible in guides are still located where they are linked from. 
- All links elsewhere within the moved pages were updated to ensure no broken links (docusarus makes that SO easy!)

Lastly, I'm proposing making a minor revert from a change earlier today that was submitted by @ajmcquilkin in #563 . Specifically, this commit: https://github.com/meshtastic/meshtastic/pull/563/commits/3274ced7a75d8b6d25cb528020bd91acff10ecf7 . While the "Docs" link pointed to `/docs/introduction` would be redundant with the "Learn More" link pointed to the same location, I think it's more appropriate at this time due to the `docs/about` page being nothing more than a navigational top page. It serves no content. Opening directly to `docs/introduction` immediately serves content to the users, and the navigational tree that was available at `docs/about` is still easily available on the sidebar. Lastly, with work being done on a new /about section, in the near future the "Learn More" link will likely point to that location, and removing the redundancy. 

Preview to changes made by this PR are available [via vercel.](https://meshtastic-docs-n5d3n75y1-rcarteraz.vercel.app)

### CODE REVIEW

**Comment by sachaw** [comment]
I like the changes, well thought out, I'll just see what some of the other Devs think

**Comment by caveman99** [comment]
+1 from me, although this makes the guides less visible and sinks/hides them in the general documentaton. OTOH most of these were created describing the solution to a particular problem, much like a blog entry.

I say go for it, rather fill the free estate with a showcase section :-)

**Review by caveman99 — APPROVED** [review]

**Comment by jfirwin** [comment]
I love it. Very well thought out. Keeping the getting started and configuration sections clean and available is important for user usability.

**Comment by sachaw** [comment]
What a coincidence, I'm working on some of the prerequisite work for this.

**Pull request merged**
