### PR TITLE
Revert "Antennas resources update"

### PR DESCRIPTION
**Pull request by lawpac10**
Reverts meshtastic/Meshtastic#57 back to its original  source ...any update asking to change or edit my account is fraudulent and shouldn't be approve by GitHub .

### CODE REVIEW

**Comment by sachaw** [comment]
Sorry, could you please elaborate on "any update asking to change or edit my account is fraudulent and shouldn't be approve by GitHub" Not entirely sure what you mean?

**Comment by sachaw** [comment]
This account appears to be spam, Will auto close this issue tomorrow

**Comment by lawpac10** [comment]
Please help me secure my account it has been comt by bad hackers .do not change any settings . Please help me secure my accounts . Make sure all mails are coming from my personal email address : lawpacmichael@gmail.com . Take note

**Comment by lawpac10** [comment]
Help me secure my accounts . Don't change any settings . Restore my account to it's original settings as it was when I first created account with GitHub .

**Comment by apt105** [comment]
Yup, definitely spam!

**Comment by sachaw** [comment]
I reported the account, should be removed soon.

**Pull request closed without merging**
