### PR TITLE
Update Trademark Grants

### PR DESCRIPTION
**Pull request by PacificNorhwest3D**
Update trademark grants to include Pacific Northwest 3D LLC

### CODE REVIEW

**Comment by PacificNorhwest3D** [comment]
> Did you follow the process to contact [trademark@meshtastic.org](mailto:trademark@meshtastic.org) for review first? Per the step 1 on [How to Request a Trademark Grant](https://meshtastic.org/docs/legal/trademark-grants/#how-to-request-a-trademark-grant)?

@rcarteraz I have followed the process and I contacted trademark@meshtastic.org prior to submitting this PR. Next, per step 2, submitted this PR with updates to the page. Should I remove my PR until I get an email back?


> Products need to use the m powered logo.

@garthvh Can you point me to the documentation referring to this requirement? Per the Licensing & Trademark Rules, it states under **non-software goods**:

_The adding our logo or other marks to a non-software good may be allowed, with written permission from the the Meshtastic Trademark Supervisior, provided that the non-software good is a 100% original design or the requester has evidence of a grant of use from copyright holder of the original design._

There are also many other 3D Printed case designs currently licenced that only have the meshtastic M logo, I'm failing to understand how my design and use of the meshtastic logo differs from what's already been approved?

The issue this poses for me is that it's very tough to print small letters consistently with my setup. It very often leads to a mangled first layer. I assume this is why other designers have also opted to use just the M logo.

**Comment by tekstrand** [comment]
@PacificNorhwest3D FYI you have a typo in your GitHub username - Nor(t)hwest

Admins are reviewing your request https://discord.com/channels/867578229534359593/1047263557525458994/1246459890520686664

**Comment by mc-hamster** [comment]
Declining request.

At this point, we're not giving out additional grants to use the Meshtastic logo on products such as described.

There are those that use our primary logo now, those have been around for a while. If you're aware of any that are using the Meshtastic logo without a grant, please do let us know and we'll be in touch with them.

To show support, the Meshtastic Powered logo is the one we have that you use to include in your products. It's similar to the "Intel Inside" logo. It indicates that you are not Meshtastic but integrate with Meshtastic.

We really appreciate your enthusiasm!

**Comment by PacificNorhwest3D** [comment]
I appreciate you taking the time to review the request for a trademark grant, I'll see if I can find a way to incorporate the 'Meshtastic Powered' logo in a way where I can consistently print these things while still maintaining a level of quality that is acceptable.

What are the restrictions on using the name **Meshtastic** in a product listing? Is this okay, or is this considered a trademark violation?

**Comment by caveman99** [comment]
@PacificNorthWest3D please refer to https://meshtastic.org/docs/legal/licensing-and-trademark/

In a nutshell: say you use meshtastic or are compatible or it is installed on the device, don't pretend to BE meshtastic or have endorsement from the LLC.

**Pull request closed without merging**
