### PR TITLE
Removed tile subcategory pages

### PR DESCRIPTION
**Pull request by pdxlocations**

### CODE REVIEW

**Comment by garthvh** [comment]
The pages are pretty important on mobile

**Comment by pdxlocations** [comment]
Ahhh, copy that, meant to pull request to my master fork to force a vercel test deployment.  Sorry!

**Comment by pdxlocations** [comment]
@rcarteraz @garthvh 
Here's a rough [demo deployment](https://sandbox-git-docusaurus-test-pdxlocations.vercel.app/) to test the concept.  I just changed the broken links to find existing pages.

**Comment by garthvh** [comment]
This is definitely not mobile first this is a change that only helps desktop users .Big touchable areas is what you want on mobile.  I want out of the tiny left nav as soon as possible.  I never want a heading that looks like a the other links that you can't click on mobile.

**Comment by pdxlocations** [comment]
All good!  It's all valuable learning experiences for me and if I can help the project in any small way, that's a bonus!

**Pull request closed without merging**
