### PR TITLE
Add Spain to local-groups.mdx

### PR DESCRIPTION
**Pull request by andresgongora**
We have a telegram group (https://t.me/meshtastic_esp) for Spain, which I've found after asking Spain's _Youngsters On The Air_ ham radio community (https://chavaladea.es/).

I've placed Spain in the list in alphabetical order.

### CODE REVIEW

**Review by pdxlocations — CHANGES_REQUESTED** [review]
Thank you for your submission!  I ask that you please review the Meshtastic Trademark Guidelines:
https://meshtastic.org/docs/legal/licensing-and-trademark/

We can't allow social media groups to use the "M" logo or be named "Meshtastic [location]".   Please reply here if you need any help or clarification making these adjustments.  I am looking forward to adding your group to the official Meshtastic Documentation.

Screenshot 2024-09-19 at 9 41 21 AM

**Comment by andresgongora** [comment]
I'm not the manager, I'm only an user, so I can't make any changes to the Telegram group.
There appears the be very little Meshtastic activity here and this group chat is the only community I found after asking around among hams.
Should this be handled by someone else, or should I close the PR?

**Comment by pdxlocations** [comment]
@andresgongora It would be appreciated if you could reach out to the admins of the Telegram group to let them know they are in violation of trademark usage.

**Comment by andresgongora** [comment]
I've forwarded the guidelines to them

**Comment by andresgongora** [comment]
The admins are already revising the name and icon of the group chat. I'll come back for a reevaluation when ready.

**Comment by QuixoteSystems** [comment]
We just updated the name and logo of the TG Group as you can see:

image

**Comment by pdxlocations** [comment]
@QuixoteSystems So sorry, the [Licensing and Trademark page ](https://meshtastic.org/docs/legal/licensing-and-trademark/#social-media)states:

>Meshtastic also grants communities and user groups permission to use the Meshtastic logo, provided it is displayed in a secondary position to the group's primary branding. For example, a hiking club's newsletter might feature their own logo prominently at the top, with the Meshtastic logo placed smaller and below, indicating the technology's support for their activities.

The logo this group is using could be mistaken for an officially endorsed group due to the prominent "M" Logo.  It is suggested that clubs use their own identifying marks or use the [M-Powered variant](https://github.com/meshtastic/design/tree/master/Meshtastic%20Powered%20Logo) of the Meshtastic Logo.

Thank you for your patience!

**Comment by andresgongora** [comment]
Would this logo, or one like it, be in accordance with the guidelines?

meshtastic

**Comment by QuixoteSystems** [comment]
We have already updated the logo in the TG Group.

TG

**Comment by pdxlocations** [comment]
> We have already updated the logo in the TG Group.

Thank you, all that remains is to change the wording in the link on this PR from "Meshtastic España" to something like: "Meshtastic Spanish Community".  Once this is updated I'll be happy to merge!

**Comment by andresgongora** [comment]
@pdxlocations Thanks. Done!

**Pull request merged**
