### PR TITLE
Add the recommendation of installing the meshtastic python package with the CLI extras packages

### PR DESCRIPTION
**Pull request by ianmcorvidae**
## What did you change
Recommends using the `[cli]` suffix to install the CLI extras for the meshtastic CLI, which since 2.5.6 separates out a couple optional dependencies for CLI nicety (color printing an QR code generation, specifically) into that section.

## Why did you change it
This is more consistent with prior versions of the CLI; those packages were made optional for the sake of packaging in less friendly environments without needing as many dependencies.

### CODE REVIEW

**Comment by pdxlocations** [comment]
The instructions are not working for me (on mac) I'm getting the error:

`zsh: no matches found: meshtastic[cli]`


```
benlipsey@El-P % python3 -m venv .venv            
benlipsey@El-P % cd .venv 
benlipsey@El-P .venv % pip install --upgrade meshtastic[cli]
zsh: no matches found: meshtastic[cli]
benlipsey@El-P .venv % pip install --upgrade meshtastic     
Requirement already satisfied: meshtastic in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2.5.5)
Collecting meshtastic
  Using cached meshtastic-2.5.6.post1-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: bleak<0.23.0,>=0.22.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from meshtastic) (0.22.3)
Requirement already satisfied: packaging<25.0,>=24.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from meshtastic) (24.0)
Requirement already satisfied: protobuf>=4.21.12 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from meshtastic) (5.26.1)
Requirement already satisfied: pypubsub<5.0.0,>=4.0.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from meshtastic) (4.0.3)
Requirement already satisfied: pyserial<4.0,>=3.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from meshtastic) (3.5)
Requirement already satisfied: pyyaml<7.0.0,>=6.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from meshtastic) (6.0.1)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from meshtastic) (2.31.0)
Requirement already satisfied: tabulate<0.10.0,>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from meshtastic) (0.9.0)
Requirement already satisfied: pyobjc-core<11.0,>=10.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from bleak<0.23.0,>=0.22.3->meshtastic) (10.3.2)
Requirement already satisfied: pyobjc-framework-CoreBluetooth<11.0,>=10.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from bleak<0.23.0,>=0.22.3->meshtastic) (10.3.2)
Requirement already satisfied: pyobjc-framework-libdispatch<11.0,>=10.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from bleak<0.23.0,>=0.22.3->meshtastic) (10.3.2)
Requirement already satisfied: typing-extensions>=4.7.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from bleak<0.23.0,>=0.22.3->meshtastic) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.31.0->meshtastic) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.31.0->meshtastic) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.31.0->meshtastic) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.31.0->meshtastic) (2024.2.2)
Requirement already satisfied: pyobjc-framework-Cocoa>=10.3.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pyobjc-framework-CoreBluetooth<11.0,>=10.3->bleak<0.23.0,>=0.22.3->meshtastic) (10.3.2)
Using cached meshtastic-2.5.6.post1-py3-none-any.whl (291 kB)
Installing collected packages: meshtastic
  Attempting uninstall: meshtastic
    Found existing installation: meshtastic 2.5.5
    Uninstalling meshtastic-2.5.5:
      Successfully uninstalled meshtastic-2.5.5
Successfully installed meshtastic-2.5.6.post1```

**Comment by ianmcorvidae** [comment]
Hm, interesting. It seems like zsh might be doing something funky with the square brackets. I think that it might work quoted, so `pip install --upgrade "meshtastic[cli]"` -- would you be able to try that out?

I guess it might be good if we can get a windows tester as well.

**Comment by pdxlocations** [comment]
Yup, it worked with quotes:
```
(.venv) benlipsey@El-P ~ % pip install --upgrade "meshtastic[cli]"
Requirement already satisfied: meshtastic[cli] in ./.venv/lib/python3.13/site-packages (2.5.6.post1)
Requirement already satisfied: bleak<0.23.0,>=0.22.3 in ./.venv/lib/python3.13/site-packages (from meshtastic[cli]) (0.22.3)
Collecting dotmap<2.0.0,>=1.3.30 (from meshtastic[cli])
  Using cached dotmap-1.3.30-py3-none-any.whl.metadata (3.2 kB)
...
```

**Comment by pdxlocations** [comment]
Works without quotes on windows:
```
C:\Users\benli>pip install --upgrade meshtastic[cli]
Requirement already satisfied: meshtastic[cli] in c:\users\benli\appdata\local\programs\python\python311\lib\site-packages (2.2.2)
Collecting meshtastic[cli]
  Downloading meshtastic-2.5.6.post1-py3-none-any.whl (291 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 291.2/291.2 kB 9.1 MB/s eta 0:00:00
...
```

**Comment by ianmcorvidae** [comment]
If you're still up to test, does it work _with_ the quotes on Windows? I'd rather have a consistent way to do it, and with the quotes works on Linux and Mac, so if it does on Windows as well then the current version should be good (I just added quotes to everywhere, heh)

**Comment by pdxlocations** [comment]
Good call.  Yes, it also works with the quotes on Windows.

**Review by pdxlocations — APPROVED** [review]

**Pull request merged**
