### PR TITLE
Add fingerprint from IzzyOnDroid's Repo

### PR DESCRIPTION
**Pull request by marek22k**
To prevent MitM attacks, it is good to add the fingerprint of the repository.

### CODE REVIEW

**Review by andrekir — APPROVED** [review]

**Comment by caveman99** [comment]
@marek22k can you please allow maintainer edits to the repo? i can#t fast forward and merge the way it is now.

**Comment by marek22k** [comment]
As long as there is no unnecessary merge again, even though there is no conflict...

**Comment by caveman99** [comment]
Problem is, the repo has a policy to only merge when your branch is up to date. I simply can#t ush the button when your copy is behind. If you allow maintainer edits i can forward te branch and then merge it.

**Comment by marek22k** [comment]
Ahh, with that background, of course it's understandable. Thanks for the clarification!

**Comment by caveman99** [comment]
Thank you for your contribution. Merged.

**Pull request merged**
