### PR TITLE
Update local-groups.mdx

### PR DESCRIPTION
**Pull request by Oliver0804**
Add taiwan

### CODE REVIEW

**Comment by Oliver0804** [comment]
Hi sir,
is there anything else needed for the PR

**Comment by pdxlocations** [comment]
Hi @Oliver0804 , regarding "Meshtastic Taiwan", you may wish to review the trademark usage guidelines for social media sites:
https://meshtastic.org/docs/legal/licensing-and-trademark/#social-media

**Comment by Oliver0804** [comment]
> Hi @Oliver0804 , regarding "Meshtastic Taiwan", you may wish to review the trademark usage guidelines for social media sites: https://meshtastic.org/docs/legal/licensing-and-trademark/#social-media

@pdxlocations  Thank you for your reply, I have read through the document.

I would like to briefly introduce the content of my PR. The structure of "Meshtastic Taiwan 臺灣鏈網" is basically the same as that of "Meshtastic North America Community" in terms of semantics. Could you please tell us more precisely how we should make corrections?

Additionally, "Meshtastic Taiwan 臺灣鏈網" has developed quite rapidly in Taiwan over the past 2 to 3 months. I think its development is relatively faster compared to other Asian countries, possibly due to political factors or the frequent earthquakes. However, I believe that the main reason for its success is the promotion efforts of its members.

**Comment by pdxlocations** [comment]
I see the group has over 2000 member.  This is incredible!  It's wonderful to see the Meshtastic community grow all over the world. I am not a member of the Meshtastic Organization, though I do my best to look out for it's best interests and help out with the documentation when I can.

The addition of "Community" or "Group" helps to distinguish the entity as it's own thing, and not an "official" Meshtastic Organization-run social media page.  Just think of a group calling itself, "Nike UK." This would not sit well with the CEO of Nike as it sounds like an arm of the company located in the UK, even if it is only a fan club.

Names such as "Meshtastic Users Taiwan" or "Taiwan Meshtastic Club" would, I believe, fall within acceptable naming conventions.  I invite you to come up with a name that fits your group and gives it a unique identity.

Again, I am in no way an authority in the matter and welcome others to comment.

**Comment by Oliver0804** [comment]
@pdxlocations Thanks for the quick reply.

but,I'm sorry, I'm going to leave this RP as it is, with other explanations, or a detailed explanation of why by the project leader

BTW, I also noticed the issue you mentioned on that page:
https://meshtastic.org/docs/community/local-groups/

截圖 2024-05-07 下午1 42 29

**Comment by pdxlocations** [comment]
> but,I'm sorry, I'm going to leave this RP as it is

No need to be sorry.  If anything, it pains me to fuss at all about a such a supportive community site like yours!


> BTW, I also noticed the issue you mentioned on that page:
> https://meshtastic.org/docs/community/local-groups/

Yes, these groups were added either before the guidelines were in place, or by accident 😳, and links may eventually be removed if the registered trademark is not respected. See: https://github.com/meshtastic/meshtastic/issues/1211

**Comment by mc-hamster** [comment]
Hello,

What a great community! Our new guidelines indicate that there needs to be a way to easily distinguish it from being a created by Meshtastic directly.

The discord group looks good as it's called "TWC Mesh"

image

but the Facebook group uses the Meshtastic logo as primary branding and it isn't clear that this is a user group.

image

Please adjust these and then the PR will be approved.

Thanks!

**Comment by Oliver0804** [comment]
截圖 2024-05-08 下午2 54 14

Thank you for the quick responses. After our internal discussion, we have updated the corresponding name and logo for Meshtastic. If there are any further updates needed, please let me know. Thank you.

**Pull request merged**
