### PR TITLE
Added Finland to the local groups

### PR DESCRIPTION
**Pull request by valzzu**
Added Finland

### CODE REVIEW

**Review by pdxlocations — CHANGES_REQUESTED** [review]
Instead of naming the links "Discord" and "website", could I suggest something like: "Mesh Finland Discord" and "Mesh Finland Website" ?
There may eventually be more groups in Finland so it would be good for the links to have specific names.

**Comment by valzzu** [comment]
> Instead of naming the links "Discord" and "website", could I suggest something like: "Mesh Finland Discord" and "Mesh Finland Website" ? There may eventually be more groups in Finland so it would be good for the links to have specific names.

Aight, ill do that.
Thx!

**Review by pdxlocations — APPROVED** [review]

**Comment by pdxlocations** [comment]
Oops sorry, could you add Finland in alphabetical order with the rest of the countries? I think they're a little out of order already, lol.

**Comment by valzzu** [comment]
Haha, alr ill do that 😅

**Comment by pdxlocations** [comment]
> Hopefully its correct now 😅

Oh my, now it's in the middle of the United States.  Things were not in alphabetical order at all before this...

**Comment by valzzu** [comment]
> > Hopefully its correct now 😅
> 
> Oh my, now it's in the middle of the United States.  Things were not in alphabetical order at all before this...

This is the funniest thing that has happened today 😅

**Comment by valzzu** [comment]
How about now 😅

**Comment by pdxlocations** [comment]
> How about now 😅

YES! Perfect.

**Comment by valzzu** [comment]
Great 😅

**Pull request merged**
