### PR TITLE
Add CLI examples

### PR DESCRIPTION
**Pull request by nigelorr**

### CODE REVIEW

**Comment by sachaw** [comment]
Please long this and I'll merge.

**Comment by nigelorr** [comment]
Thanks, first PR and first md edit, could you point me to process to follow or specific problem to resolve?

**Comment by jfirwin** [comment]
First off, thank you for contributing! If you haven't already. Try setting up a [Vercel](https://vercel.com) account and associate it with your Github and your fork of this project. This will allow you to see your changes on a live site.

I noticed you put an admonition into the tabs (`:::note`). Make sure that the colons are the first character on the line they are in. Also make sure you add a new line with the closing `:::` after your note. See an example [here](https://github.com/meshtastic/Meshtastic/blame/5a98e0c82d4bba1022c291228a1124ab249e8670/website/docs/software/settings/overview.md#L45-L47)

**Comment by sachaw** [comment]
As for auto linting, please use vscode as your editor with the Prettier extension, I'll add this to the workspace recommendations, so you should get prompted to install it in the future.

**Comment by nigelorr** [comment]
Thanks @sachaw for the helpful detail. Now reformatted with Prettier.

@jfirwin fixed note syntax, couldn't get it working with first attempt in Vercel but will try again if I do any more substantial edits.

**Comment by jfirwin** [comment]
Thanks again for your contribution!

**Pull request merged**
