### PR TITLE
External GPS module instructions

### PR DESCRIPTION
**Pull request by danpeig**
Instructions on how to use external GPS modules on boards without this functionality. I plan to do the same for other simple boards as soon as I am able to test it properly.

### CODE REVIEW

**Comment by jfirwin** [comment]
Work is crazy today so I probably won't look too closely at this until tomorrow.

On first glance though I noticed `sidebar.js` has not been modified so your page won't show up on the sidebar. You'll need to add `"hardware/gpsmodule"` to the appropriate spot in that file to get it to show up. Maybe nested. Not sure on how we want it at the moment.

Thanks for the contribution!

**Comment by danpeig** [comment]
Oh... the JS file was completely out of my radar. I updated it.

**Comment by jfirwin** [comment]
I looked at this briefly yesterday. With your recent updates do you feel like it's ready to merge?

**Comment by danpeig** [comment]
I was delayed by an unsupported version of Node in my computer... Now that I compiled the page I see there are no updates pending. It is ready to go.

**Comment by jfirwin** [comment]
I'm still learning how to handle the merge conflicts so I've requested a review. We'll get this added in. Thanks for your contribution!

**Comment by sachaw** [comment]
Merged in #290 661d617cb10a7dc5a1f9d30fcb619e8e667c1878

**Pull request closed without merging**
