### PR TITLE
Settings enhancments

### PR DESCRIPTION
**Pull request by jfirwin**
Still a work in progress, but I promised it a week ago and haven't had time to touch much of it. Want to get it out there though so I'll fix anything found in a future PR. Available to view [here](https://meshtastic-git-settings-enhancments-jfirwin.vercel.app/docs/settings)

- Updated overview page to explain some basics and point users to common settings
- added CLI examples to many of the pages
- added CLI example placeholders to some settings I haven't felt comfortable messing with yet (looking at you, advanced channel settings... don't want to fry my radio to write documentation) I will be adding admonitions to things that can potentially damage the radio once I get those examples figured out.

### CODE REVIEW

**Review by apt105 — COMMENTED** [review]
Good effort!! That's a lot of work, looks pretty good!

**Comment by jfirwin** [comment]
Thank you! I need to add an admonition to the unavailable platform settings (Android/web/iOS). Something like:
```
:::note
This setting is currently not able to be changed using the x app. If this is something you would like added, please submit a pull request or file an issue on the [meshtastic-x repository](linkurl)
:::
```
I may need to buy an old android phone to write those up. I tried running a x86 version of android on Virtualbox on MacOS but ran into some hiccups with passing the bluetooth from the host to the VM

**Comment by sachaw** [comment]
Merging this now, Just make any alterations in a new PR.

**Comment by jfirwin** [comment]
Thank you! Will do.

**Pull request merged**
