### PR TITLE
Add new button combination to LoRa 32 Buttons page - Update buttons.mdx

### PR DESCRIPTION
**Pull request by mtsdawson**
This is my first doc edit.  Please let me know if there's a procedure I can reference or if you need additional info, thanks.

### CODE REVIEW

**Comment by mtsdawson** [comment]
Well that would explain the battery drain. Feel free to close this out.
________________________________

**Comment by tekstrand** [comment]
Maybe still good to document?

**Comment by mtsdawson** [comment]
Yeah, it might help others avoid my mistake. The LCD shuts off, so it does lead one to think it's a full shutdown.

**Comment by pdxlocations** [comment]
@mtsdawson thank you for contributing, I'll close this one since it appears to be inaccurate but don't let that discourage future edits!

**Pull request closed without merging**
