### PR TITLE
faq click sets hash in url for scrolling

### PR DESCRIPTION
**Pull request by tekstrand**

### CODE REVIEW

**Comment by tekstrand** [comment]
@pdxlocations @rcarteraz here is a working "scroll to last clicked item". Only problem I am seeing is that every time you open an FAQ item it scroll it to the top of the page and feels very weird. What do y'all think?

**Comment by pdxlocations** [comment]
> @pdxlocations @rcarteraz here is a working "scroll to last clicked item". Only problem I am seeing is that every time you open an FAQ item it scroll it to the top of the page and feels very weird. What do y'all think?

oh, I don NOT like that.

**Comment by tekstrand** [comment]
I agree. What do y'all think the ideal behavior is?

**Comment by pdxlocations** [comment]
it's weird that these links send  you halfway down the page
https://meshtastic.org/docs/faq/?#modules

**Comment by tekstrand** [comment]
Maybe we can add a specific link button like headings have? You can click it, it updates the url, and then you can copy that?

**Pull request closed without merging**
