### PR TITLE
Revert "Update trademark-grants.mdx"

### PR DESCRIPTION
**Pull request by mc-hamster**
Reverts meshtastic/meshtastic#952

### CODE REVIEW

**Comment by mc-hamster** [comment]
Reverting trademark grant to ikb3d.co.uk

**Review by tekstrand — APPROVED** [review]
Not sure if I am "allowed" to approve this, but approved!

**Comment by mc-hamster** [comment]
> Not sure if I am "allowed" to approve this, but approved!

Lol :)

**Comment by mc-hamster** [comment]
@IKB3D please contact trademark@meshtastic.org  .

Thanks!

**Pull request merged**
