### PR TITLE
initial sponsor page

### PR DESCRIPTION
**Pull request by jfirwin**
closes issue #344.

It was brought to my attention that "Donate" may have specific meaning in some areas, and that we should name the page "sponsor" This is my work in progress to add that page.

### CODE REVIEW

**Comment by thebentern** [comment]
Would this be a good place to mention other parters like Vercel for instance who have given us premium services?

**Comment by jfirwin** [comment]
I think that would be a great place! Do we have a comprehensive list of companies/services? I'd like to showcase their logos under a section on the page.

**Comment by jfirwin** [comment]
changing sponsors page to credits page. I'll open a new pr shortly

**Comment by jfirwin** [comment]
I'm creating a new branch to make the credits page. Will submit soon.

**Pull request closed without merging**
