### PR TITLE
redid flashing firmware section with tabs

### PR DESCRIPTION
**Pull request by jfirwin**
Available for viewing [here](https://meshtastic-git-flashing-firmware-tabs-jfirwin.vercel.app/docs/getting-started/flashing-firmware)

### CODE REVIEW

**Comment by sachaw** [comment]
Looks good, ready to merge?

**Comment by jfirwin** [comment]
I believe so! Most of it was copy paste into a new format, so fixes should be easy if there's anything required.

**Comment by apt105** [comment]
Looks good, I like it's linked!

**Comment by jfirwin** [comment]
I'm really happy with the tab functionality. It's going to be fun to implement. It really elevates the docs to professional looking.

**Pull request merged**
