### PR TITLE
Update local-groups.mdx

### PR DESCRIPTION
**Pull request by Kavitate**
Added midwest mesh group for qualifying states.

### CODE REVIEW

**Comment by pdxlocations** [comment]
I'm going to hold off approving this unless an admin approves the use of the Meshtastic Trademark on your Discord Server.  Alternatively you may wish to create a unique brand for your club.

image

**Comment by Kavitate** [comment]
I can change it to "Midwest Mesh" and change the logo if needed.

**Comment by Kavitate** [comment]
@pdxlocations I've updated the group name and server logo.

**Comment by pdxlocations** [comment]
Thanks!  OK, now I'm not too keen on linking 6 times from different states.  I don't believe that's how the page was intended to be used.  If you're not associated with particular state, my opinion would be to pick one, or just list it as a group under United States, NOT affiliated with a state.

See how PDXMesh mentions WA in the description and/or how UK has a "North East England" link

**Comment by Kavitate** [comment]
@pdxlocations I wasn't sure how they would want them listed since the U.S is broken down by states and no one has done a region yet. Anyway, I've created the "Midwest Region" under the U.S and added the group in there.

**Comment by pdxlocations** [comment]
I think we can leave out the Midwest Region header. If someday there are more Midwest clubs we can add the header back in.  Open to other ideas of course.

**Comment by Kavitate** [comment]
Removed the Midwest Region header.

**Review by pdxlocations — APPROVED** [review]

**Pull request merged**
