### PR TITLE
Update local-groups.mdx

### PR DESCRIPTION
**Pull request by elranr**
Added Israel Meshtastic club telegram group

### CODE REVIEW

**Comment by garthvh** [comment]
Is meshtastic legal is Israel? Previous research indicates no..

**Review by pdxlocations — APPROVED** [review]
I hope you don't mind I edited your PR to correct the order and header level

**Comment by tekstrand** [comment]
> Is meshtastic legal is Israel? Previous research indicates no..

Do you recall why it was be illegal? I believe the 915mhz ISM band is allowed there.

**Comment by garthvh** [comment]
Looks like Lora would require a 1% duty cycle

**Comment by caveman99** [comment]
> Looks like Lora would require a 1% duty cycle

Yea, but couldn't a user group also be advocating to make it legal? Having a local group is not illegal per se, so i think we can accept the listing.

**Review by tekstrand — APPROVED** [review]

**Pull request merged**
