### PR TITLE
Move Enclosures into Community Section

### PR DESCRIPTION
**Pull request by pdxlocations**
This PR moves all enclosures out of the hardware section and into the new Community area.  These are not enclosures from the manufacturer but rather designs from our community. 
[preview link](https://sandbox-git-community-enclosures-pdxlocations.vercel.app/docs/category/enclosures)

### CODE REVIEW

**Comment by pdxlocations** [comment]
I haven't added any redirects because:
- I believe each section would need it's own due to renaming the pages.
- These aren't core Meshtastic features and easily found in multiple locations online.

**Review by charminULTRA — APPROVED** [review]
Placement looks good in the Preview vs. existing

**Comment by muzidesign** [comment]
Can I add my Heltec V3 case to this?

**Comment by pdxlocations** [comment]
> Can I add my Heltec V3 case to this?

Definitely, let me merge this one first, then feel free to open a PR to add your case

**Pull request merged**
