### PR TITLE
Update local-groups.mdx

### PR DESCRIPTION
**Pull request by Shogoc**
Updated to add Kansas City metro local groups in Kansas and Missouri

### CODE REVIEW

**Review by Reid-n0rc — APPROVED** [review]
This is correct

**Review by Reid-n0rc — APPROVED** [review]

**Review by tekstrand — CHANGES_REQUESTED** [review]
Thanks for the PR! Can you please update the name of the Facebook group to meet the guidelines? The text here already meets them, but the actual group name on Facebook does not. https://meshtastic.org/docs/legal/licensing-and-trademark/#social-media

Screenshot 2024-06-01 at 8 50 37 AM

**Comment by Shogoc** [comment]
> Thanks for the PR! Can you please update the name of the Facebook group to meet the guidelines? The text here already meets them, but the actual group name on Facebook does not. https://meshtastic.org/docs/legal/licensing-and-trademark/#social-media
> 
> Screenshot 2024-06-01 at 8 50 37 AM

If I'm reading the usage guidelines, the group should be "Kansas City Meshtastic" vs "Kansas City meshtastic"? 
I'm not the owner of the group but would be more than happy to request the change.

**Comment by Shogoc** [comment]
> Thanks for the PR! Can you please update the name of the Facebook group to meet the guidelines? The text here already meets them, but the actual group name on Facebook does not. https://meshtastic.org/docs/legal/licensing-and-trademark/#social-media

The Facebook page has been updated: 

kc-meshtastic-community

**Review by tekstrand — APPROVED** [review]
Thank you for making the update!

**Pull request merged**
