### PR TITLE
Update local-groups.mdx

### PR DESCRIPTION
**Pull request by cfultz**
## What did you change

Local Groups page to add Shenandoah Valley Meshtastic 

## Why did you change it

Add visibility to the group to engage with other folks in the Shenandoah Valley area

### CODE REVIEW

**Comment by pdxlocations** [comment]
@cfultz Would you sign the CLA so we may review your submission?

@rcarteraz What's your take on the [trademark licensing guide lines](https://meshtastic.org/docs/legal/licensing-and-trademark/#social-media) in this case?
Screenshot 2024-12-27 at 10 37 02 AM

**Comment by cfultz** [comment]
@pdxlocations Signed! 

@rcarteraz and @pdxlocations, if anything needs to be changed with that (the logo in full or even the site url), we are ready to do so as to not impose on copyright.

**Comment by cfultz** [comment]
> > @cfultz Would you sign the CLA so we may review your submission?
> > @rcarteraz What's your take on the [trademark licensing guide lines](https://meshtastic.org/docs/legal/licensing-and-trademark/#social-media) in this case? Screenshot 2024-12-27 at 10 37 02 AM
> 
> That needs to be updated as it’s not secondary. Also the name is not acceptable either.

Understood. Will make the changes now and disable access to that web domain.

**Comment by cfultz** [comment]
> > > > @cfultz Would you sign the CLA so we may review your submission?
> > > > @rcarteraz What's your take on the [trademark licensing guide lines](https://meshtastic.org/docs/legal/licensing-and-trademark/#social-media) in this case? Screenshot 2024-12-27 at 10 37 02 AM
> > > 
> > > 
> > > That needs to be updated as it’s not secondary. Also the name is not acceptable either.
> > 
> > 
> > Understood. Will make the changes now and disable access to that web domain.
> 
> Thank you. There’s info in the link @pdxlocations provided and you can also see examples in the list here as to what is acceptable.

I'll review and re-instate with the modifications and resubmit for review. Thank you both!

**Comment by cfultz** [comment]
Changed url to svmesh.org and corrected the logo to remove the entire meshtastic logo and added "users group" to our name. Do i need to completely resubmit this pull?

**Review by cfultz — COMMENTED** [review]
Change made for URL

**Pull request merged**
