### PR TITLE
New FAQ Component

### PR DESCRIPTION
**Pull request by tekstrand**
## What
1. Adds a new FAQ componenet to the site with collapsible sections
    - Uses [react-accessible-accordion](https://github.com/springload/react-accessible-accordion)
    - Supports linking/preExpanded questions by adding query params to the URL as users interact with the FAQs
    - Doesn't currently support scrolling to an open question
    - Supports [Structured Data Markup](https://developers.google.com/search/docs/appearance/structured-data/faqpage) for Search engines

### Site
Screenshot 2024-02-13 at 4 39 47 PM
Screenshot 2024-02-13 at 4 39 43 PM
Screenshot 2024-02-13 at 4 39 39 PM
Screenshot 2024-02-13 at 4 39 35 PM

### Structured Data Testing Tool Verification
Screenshot 2024-02-13 at 9 53 51 PM
Screenshot 2024-02-13 at 9 53 40 PM

### CODE REVIEW

**Comment by pdxlocations** [comment]
Nice!  This is looking great.

**Comment by pdxlocations** [comment]
I love the concept here.  Much easier to read when the answers are opt-in.
Dark mode looks a little wonky.
Some answers will need to be expanded in a separate PR so it's not just a link.
Screenshot 2024-02-13 at 9 35 09 AM

**Comment by tekstrand** [comment]
Yeah the styles are bad right now. Just using some precompiled theme.

No rush @rcarteraz

**Comment by tekstrand** [comment]
Great question...I'll need to dig into the Algolia integration to answer that. Is there someone who is most familiar with that right now?

**Comment by pdxlocations** [comment]
> Great question...I'll need to dig into the Algolia integration to answer that. Is there someone who is most familiar with that right now?

It might be you 😜. (Or @sachaw)

I now am wondering if this type of integration will make things difficult in the future in the same way tabs have.

**Comment by tekstrand** [comment]
I did think about the tabs -> PDF thing. This should be easier to solve, if we still want to do it. Also, the plugin I am using for the accordion meets w3c accessibility requirements so we're good there.

I'll start looking into Algolia :P I _might_ need access, but I don't think so.

**Comment by tekstrand** [comment]
Okay this was a lot simpler than I expected. The [Docusaurus Algolia](https://docusaurus.io/docs/search#using-algolia-docsearch) integration just uses Algolia's web scraper which indexes the site 1/week. This FAQ/accordion approach will work fine with our search because it is rendered on page 👍

**Comment by tekstrand** [comment]
I am taking back my statement about this being ready, I am not satisfied with the structured data performance for SERPs as it stands. Need to work out some issues. Will update this in the coming days and mark as ready when I am done.

**Comment by tekstrand** [comment]
Came up with a pretty easy fix. All of the FAQ arrays have now been combined into a single object which is passed to individual components. The structured data markup is now split into it's own component as well. You can see screenshots via [Google's search testing tool](https://search.google.com/test/) that the markup for FAQ is now valid.

**Comment by tekstrand** [comment]
Whoops. Here's the correct link for the testing tool https://search.google.com/test/rich-results

Colors have been updated to match, I was struggling to decide which looked better. It's tricky balancing light mode/dark mode.

Scrolling...I spent a fair amount of time trying to get this working. It's really tricky because of the React render lifecycle. I'll keep working on it, but I'd love to get this merged and then come back and add it later.

**Review by pdxlocations — APPROVED** [review]

**Comment by tekstrand** [comment]
giphy

**Pull request merged**
